### ISSUE TITLE
Terminal gets stuck deploying on "node ."

### ISSUE THREAD

**Issue by DoomsickIe** [Titanium-Network/Ultraviolet-Node#1]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

Deploying follows through and completes every command.
## Current Behavior

Deploying freezes on the command "node ." which serves the page and proxy itself.
## Possible Solution

Not entirely sure, as I do not develop with node
## Steps to Reproduce

1. Clone/fork repo
2. Deploy it to any VM-supported hosting service
3. Watch logs and notice nothing happen when it says "node ."

## Context (Environment)

I set up this proxy last year for my buds at school. It worked fine, nothing was wrong. But this year it seems a change was made that prevents it from deploying properly at all.

## Detailed Description

I've tried countless hosting services (Heroku, Fly.io, Cyclic) and all of them have the same issue of not being able to run the index.js/mjs in node. Absolutely no clue why.

**Comment by notAperson535** [comment]
@DoomsickIe download the contents of https://github.com/Titanium-Network/Ultraviolet-Static and put them in the `static` folder

**Comment by DoomsickIe** [comment]
thanks
